; ---------------------------------------------------------------------------
; O2om — Localization & Multi-language Support (Arabic Default / English)
; ---------------------------------------------------------------------------

class O2omLang {
    static currentLang := "ar"

    static dict := Map(
        "ar", Map(
            "app_title",            "قُوم — O2om",
            "tab_timer",            "المؤقت",
            "tab_settings",         "الإعدادات",
            "status_next_break",    "الاستراحة القادمة خلال...",
            "status_on_break",      "وقت الاستراحة! متبقي:",
            "status_idle",          "المستخدم غير نشط — توقف مؤقت",
            "status_paused",        "المؤقت متوقف مؤقتاً",
            "status_escalation_1",  "تنبيه أول: حان وقت الوقوف!",
            "status_escalation_2",  "تنبيه أخير: يرجى التحرك الآن!",
            "btn_reset",            "إعادة ضبط",
            "btn_pause",            "إيقاف مؤقت",
            "btn_resume",           "استئناف",
            "btn_start_break",      "بدء الاستراحة فقط",
            "btn_start_exercises",  "بدء التمارين (ملء الشاشة)",
            "btn_start_work",       "بدء العمل",
            "btn_snooze",           "تأجيل (غفوة)",
            "btn_save",             "حفظ الإعدادات",
            "chk_startup",          "البدء تلقائياً مع تشغيل Windows",
            "lbl_language",         "اللغة:",
            "lbl_work_min",         "فترة العمل (دقائق):",
            "lbl_short_break_min",  "الاستراحة القصيرة (دقائق):",
            "lbl_long_break_min",   "الاستراحة الطويلة (دقائق):",
            "lbl_escalation_min",   "فترة التنبيه (دقائق):",
            "lbl_snooze_min",       "مدة التأجيل (دقائق):",
            "lbl_idle_min",         "حد الخمول (دقائق):",
            "lbl_cycles_before_long", "الجولات قبل الاستراحة الطويلة:",
            "lbl_sound_enabled",      "تفعيل التنبيهات الصوتية",
            "status_cycle_badge",     "الجولة {1} من {2}",
            "msg_saved",            "تم حفظ الإعدادات بنجاح.",
            "msg_invalid_input",    "جميع الفترات يجب أن تكون بين 1 و 180 دقيقة.",
            "toast_break_title",    "O2om (قُوم)",
            "toast_break_stage1",   "حان وقت الاستراحة! قم للوقوف والتمدد.",
            "toast_break_stage2",   "تنبيه إضافي: مرت فترة الاستراحة، يرجى القيام والتحرك!",
            "toast_break_stage3",   "التنبيه الأخير: تم إعادة تشغيل المؤقت تلقائياً.",
            "toast_break_ended",    "انتهت الاستراحة! حان وقت العودة للعمل.",
            "tray_show",            "إظهار لوحة التحكم",
            "tray_pause",           "إيقاف مؤقت",
            "tray_resume",          "استئناف",
            "tray_take_break",      "بدء استراحة سريعة",
            "tray_reset",           "إعادة ضبط المؤقت",
            "tray_sound_mute",      "كتم الصوت",
            "tray_sound_unmute",    "تفعيل الصوت",
            "tray_quit",            "إغلاق التطبيق"
        ),
        "en", Map(
            "app_title",            "O2om — Stand-Up Reminder",
            "tab_timer",            "Timer",
            "tab_settings",         "Settings",
            "status_next_break",    "Next break in...",
            "status_on_break",      "Break time! Remaining:",
            "status_idle",          "User inactive — Paused",
            "status_paused",        "Timer Paused",
            "status_escalation_1",  "First Warning: Time to stand up!",
            "status_escalation_2",  "Final Warning: Please move now!",
            "btn_reset",            "Reset",
            "btn_pause",            "Pause",
            "btn_resume",           "Resume",
            "btn_start_break",      "Start Break (Tray Only)",
            "btn_start_exercises",  "Start Exercises (Fullscreen)",
            "btn_start_work",       "Start Work",
            "btn_snooze",           "Snooze",
            "btn_save",             "Save Settings",
            "chk_startup",          "Start automatically with Windows",
            "lbl_language",         "Language:",
            "lbl_work_min",         "Work Interval (min):",
            "lbl_short_break_min",  "Short Break (min):",
            "lbl_long_break_min",   "Long Break (min):",
            "lbl_cycles_before_long", "Cycles Before Long Break:",
            "lbl_escalation_min",   "Warning Interval (min):",
            "lbl_snooze_min",       "Snooze Duration (min):",
            "lbl_idle_min",         "Idle Threshold (min):",
            "lbl_sound_enabled",      "Enable Sound Notifications",
            "status_cycle_badge",     "Cycle {1} of {2}",
            "msg_saved",            "Settings updated successfully.",
            "msg_invalid_input",    "All interval values must be between 1 and 180 minutes.",
            "toast_break_title",    "O2om — Stand-Up Reminder",
            "toast_break_stage1",   "Time for a break! Stand up and stretch.",
            "toast_break_stage2",   "Additional reminder: break time has passed, please get up!",
            "toast_break_stage3",   "Final warning: timer has been auto-reset.",
            "toast_break_ended",    "Break finished! Back to work.",
            "tray_show",            "Show Dashboard",
            "tray_pause",           "Pause Timer",
            "tray_resume",          "Resume Timer",
            "tray_take_break",      "Take Break Now",
            "tray_reset",           "Reset Timer",
            "tray_sound_mute",      "Mute Sound",
            "tray_sound_unmute",    "Unmute Sound",
            "tray_quit",            "Quit O2om"
        )
    )

    static Get(key) {
        langMap := this.dict.Has(this.currentLang) ? this.dict[this.currentLang] : this.dict["ar"]
        return langMap.Has(key) ? langMap[key] : key
    }
}
